# Generated by Django 5.2 on 2025-04-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecoveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("wallet_address", models.CharField(max_length=255)),
                (
                    "crypto_type",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("USDT", "Tether"),
                            ("BNB", "Binance Coin"),
                            ("ADA", "Cardano"),
                            ("XRP", "Ripple"),
                            ("DOGE", "Dogecoin"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("issue_description", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
