# Generated by Django 5.1.1 on 2025-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_item_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
