# Generated by Django 5.2.1 on 2025-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("sender_address", models.CharField(max_length=255)),
                ("receiver_address", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
