# Generated by Django 5.2.1 on 2025-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restapi_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="transaction_id",
            field=models.CharField(max_length=255),
        ),
    ]
