# Generated by Django 5.2.1 on 2025-06-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restapi_app", "0002_alter_blockchaintransaction_amount_and_more"),
        ("Restapi_app", "0003_initial"),
    ]

    operations = []
